#pragma once
#include "Define.h"

enum ShipType{
	SHIP_NONE,
	AIRCRAFT,
	BATTLESHIP,
	CRUISER,
	DESTROYER,
};

enum ShipCount
{
	AIRCRAFT_COUNT = 1,
	BATTLESHIP_COUNT = 1,
	CRUISER_COUNT = 1,
	DESTROYER_COUNT = 2,
	TOTAL_COUNT = 5,	
};

enum HitResult{
	NONE,
	MISS,
	HIT,
	DESTROY,
	AIRCRAFT_DESTROY,
	BATTLESHIP_DESTROY,
	CRUISER_DESTROY,
	DESTROYER_DESTROY
};

enum Direction{
	NONEDIR,
	HORIZON = DIRECTIONMESSAGE_Y + MESSAGE_INTERVAL,
	VERTICAL = DIRECTIONMESSAGE_Y + MESSAGE_INTERVAL * 2
};

enum GameMode{
	NONE_MODE,
	AI_vs_AI_MODE = MAINMENU_Y + MENU_INTERVAL,
	Player_vs_AI_MODE = MAINMENU_Y + MENU_INTERVAL * 2 ,
	Player_vs_Player_MODE = MAINMENU_Y + MENU_INTERVAL * 3
};

enum DeadType{
	NONE_DEAD,
	PLAYER1_DEAD,
	PLAYER2_DEAD
};

enum PlayerType{
	NONE_PLAYER,
	AI_PLAYER,
	USER_PLAYER
};

enum AttackResult{
	NONE_ATTACK,
	ALREADY_ATTACK,
	INVALID_ATTACK,
	VALID_ATTACK
};

enum GameStatus{
	GAME_START,
	GAME_END = ENDMENU_Y + MENU_INTERVAL,
	GAME_RESTART = ENDMENU_Y + MENU_INTERVAL * 2
};